Added User entity
dimfay/ToDoList pull request #7
Opened 2022-02-14 10:46 UTC by dimfay

2022-02-14 11:06 UTC, BoomEaro requested changes

2022-02-14 11:06 UTC, BoomEaro commented on src/main/java/ru/team/todo/managers/TaskService.java
> +        }
Чтобы избежать подобного, наверное стоит сделать метод, который вернет Task по указанному ид, а если указанный индекс меньше нуля или больше чем количество элементов в массиве, возвращать нулл.

2022-02-14 11:06 UTC, BoomEaro commented on src/main/java/ru/team/todo/managers/TaskService.java
> +    }
Было бы не плохо переделать это в метод который я описал чуть выше

2022-02-14 11:06 UTC, BoomEaro commented on src/main/java/ru/team/todo/objects/User.java
> +    private int idSequence = 1;
Можно было не инициализировать name и idSequence, а передавать эти параметры в конструкторе

2022-02-14 11:06 UTC, BoomEaro commented on src/main/java/ru/team/todo/objects/User.java
> +    }
Костыль) Думаю лучше такое делать в сервисе, а при создании пользователя передавать ему этот ид.

2022-02-14 11:06 UTC, BoomEaro commented on src/main/java/ru/team/todo/ui/Menu.java
> +	}
Можно было не создавать еще один хешмап, а просто в этот же добавлять команды, но с другими названиями. Не очень понятно зачем это было сделано)

2022-02-14 13:40 UTC, msharArtiom approved these changes

2022-02-14 13:47 UTC, msharArtiom approved these changes

2022-02-14 15:29 UTC, merged

2022-02-16 16:18 UTC, javagururt commented on src/main/java/ru/team/todo/ToDoApplication.java
> +        UserService userService = new UserService();
используйте var

2022-02-16 16:20 UTC, javagururt commented on src/main/java/ru/team/todo/managers/TaskService.java
> +	User user;
будут проблемы с многопоточностью, сегодня (16.02.2022) на занятии расскажу

2022-02-16 16:21 UTC, javagururt commented on src/main/java/ru/team/todo/managers/TaskService.java
> +        if (isValidId(id)) {
не нужно проверять id который передали, по сути или удалишь или нет

2022-02-16 16:21 UTC, javagururt commented on src/main/java/ru/team/todo/managers/TaskService.java
> +	public List<Task> getAllTasks() { return tasks; }
отформатируйте класс

2022-02-16 16:22 UTC, javagururt commented on src/main/java/ru/team/todo/managers/TaskService.java
> +        	tasks.remove(id);
id != позиция в коллекции

2022-02-16 16:24 UTC, javagururt commented on src/main/java/ru/team/todo/objects/User.java
> +    private String name = "";
нет смысла делать пустую строку как дефолтное имя - лишь конфьюзит

2022-02-16 16:24 UTC, javagururt commented on src/main/java/ru/team/todo/objects/User.java
> +public class User {
formatting

2022-02-16 16:25 UTC, javagururt commented on src/main/java/ru/team/todo/ui/Menu.java
> +		this.userService = taskService.getUserService();
taskService создает userService? А иначе почему геттер?